/*
Adder API

Adder API

API version: v1
Contact: support@blinklabs.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the PushErrorResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PushErrorResponse{}

// PushErrorResponse struct for PushErrorResponse
type PushErrorResponse struct {
	Error *string `json:"error,omitempty"`
}

// NewPushErrorResponse instantiates a new PushErrorResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPushErrorResponse() *PushErrorResponse {
	this := PushErrorResponse{}
	return &this
}

// NewPushErrorResponseWithDefaults instantiates a new PushErrorResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPushErrorResponseWithDefaults() *PushErrorResponse {
	this := PushErrorResponse{}
	return &this
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *PushErrorResponse) GetError() string {
	if o == nil || IsNil(o.Error) {
		var ret string
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PushErrorResponse) GetErrorOk() (*string, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *PushErrorResponse) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given string and assigns it to the Error field.
func (o *PushErrorResponse) SetError(v string) {
	o.Error = &v
}

func (o PushErrorResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PushErrorResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	return toSerialize, nil
}

type NullablePushErrorResponse struct {
	value *PushErrorResponse
	isSet bool
}

func (v NullablePushErrorResponse) Get() *PushErrorResponse {
	return v.value
}

func (v *NullablePushErrorResponse) Set(val *PushErrorResponse) {
	v.value = val
	v.isSet = true
}

func (v NullablePushErrorResponse) IsSet() bool {
	return v.isSet
}

func (v *NullablePushErrorResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePushErrorResponse(
	val *PushErrorResponse,
) *NullablePushErrorResponse {
	return &NullablePushErrorResponse{value: val, isSet: true}
}

func (v NullablePushErrorResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePushErrorResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
