// Copyright 2026 Blink Labs Software
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package plugin

import (
	"testing"

	"github.com/spf13/pflag"
)

// TestAddToFlagSet verifies each option type registers a flag with the
// expected derived name and default, and that custom flag names work.
func TestAddToFlagSet(t *testing.T) {
	var (
		strDest  string
		boolDest bool
		intDest  int
		uintDest uint
	)
	fs := pflag.NewFlagSet("test", pflag.ContinueOnError)

	opts := []PluginOption{
		{
			Name:         "host",
			Type:         PluginOptionTypeString,
			DefaultValue: "localhost",
			Dest:         &strDest,
		},
		{
			Name:         "enabled",
			Type:         PluginOptionTypeBool,
			DefaultValue: true,
			Dest:         &boolDest,
		},
		{
			Name:         "count",
			Type:         PluginOptionTypeInt,
			DefaultValue: 7,
			Dest:         &intDest,
		},
		{
			Name:         "size",
			Type:         PluginOptionTypeUint,
			DefaultValue: uint(3),
			Dest:         &uintDest,
		},
	}
	for i := range opts {
		if err := opts[i].AddToFlagSet(fs, "output", "demo"); err != nil {
			t.Fatalf("AddToFlagSet error for %q: %v", opts[i].Name, err)
		}
	}

	// Derived names: <type>-<plugin>-<name>.
	for _, name := range []string{
		"output-demo-host", "output-demo-enabled",
		"output-demo-count", "output-demo-size",
	} {
		if fs.Lookup(name) == nil {
			t.Errorf("expected flag %q registered", name)
		}
	}
	// Defaults applied to dests.
	if strDest != "localhost" {
		t.Errorf("strDest = %q, want localhost", strDest)
	}
	if !boolDest {
		t.Error("boolDest = false, want true")
	}
	if intDest != 7 {
		t.Errorf("intDest = %d, want 7", intDest)
	}
	if uintDest != 3 {
		t.Errorf("uintDest = %d, want 3", uintDest)
	}
}

// TestAddToFlagSetCustomFlag verifies CustomFlag overrides the derived
// name (using <type>-<customflag>).
func TestAddToFlagSetCustomFlag(t *testing.T) {
	var dest string
	fs := pflag.NewFlagSet("test", pflag.ContinueOnError)
	opt := PluginOption{
		Name:         "host",
		CustomFlag:   "url",
		Type:         PluginOptionTypeString,
		DefaultValue: "",
		Dest:         &dest,
	}
	if err := opt.AddToFlagSet(fs, "output", "demo"); err != nil {
		t.Fatalf("AddToFlagSet error: %v", err)
	}
	if fs.Lookup("output-url") == nil {
		t.Error("expected custom flag output-url registered")
	}
	if fs.Lookup("output-demo-host") != nil {
		t.Error("derived flag should not exist when CustomFlag is set")
	}
}

// TestAddToFlagSetUnknownType verifies an unknown option type errors.
func TestAddToFlagSetUnknownType(t *testing.T) {
	fs := pflag.NewFlagSet("test", pflag.ContinueOnError)
	opt := PluginOption{Name: "bad", Type: PluginOptionType(99)}
	if err := opt.AddToFlagSet(fs, "output", "demo"); err == nil {
		t.Fatal("expected error for unknown option type, got nil")
	}
}

// TestProcessEnvVarsAutoGenerated verifies the auto-generated env var
// (prefix + uppercased, dashes -> underscores) is honored for each type
// with correct coercion.
func TestProcessEnvVarsAutoGenerated(t *testing.T) {
	var (
		strDest  string
		boolDest bool
		intDest  int
		uintDest uint
	)
	// Auto env var = uppercase(prefix + name) with - -> _.
	t.Setenv("OUTPUT_DEMO_HOST", "example.com")
	t.Setenv("OUTPUT_DEMO_ENABLED", "true")
	t.Setenv("OUTPUT_DEMO_COUNT", "-5")
	t.Setenv("OUTPUT_DEMO_SIZE", "42")

	prefix := "output-demo-"
	cases := []PluginOption{
		{Name: "host", Type: PluginOptionTypeString, Dest: &strDest},
		{Name: "enabled", Type: PluginOptionTypeBool, Dest: &boolDest},
		{Name: "count", Type: PluginOptionTypeInt, Dest: &intDest},
		{Name: "size", Type: PluginOptionTypeUint, Dest: &uintDest},
	}
	for i := range cases {
		if err := cases[i].ProcessEnvVars(prefix); err != nil {
			t.Fatalf("ProcessEnvVars error for %q: %v", cases[i].Name, err)
		}
	}
	if strDest != "example.com" {
		t.Errorf("strDest = %q, want example.com", strDest)
	}
	if !boolDest {
		t.Error("boolDest = false, want true")
	}
	if intDest != -5 {
		t.Errorf("intDest = %d, want -5", intDest)
	}
	if uintDest != 42 {
		t.Errorf("uintDest = %d, want 42", uintDest)
	}
}

// TestProcessEnvVarsCustomEnvVar verifies a CustomEnvVar is also checked.
func TestProcessEnvVarsCustomEnvVar(t *testing.T) {
	var dest string
	t.Setenv("MY_CUSTOM_HOST", "custom-host")
	opt := PluginOption{
		Name:         "host",
		CustomEnvVar: "MY_CUSTOM_HOST",
		Type:         PluginOptionTypeString,
		Dest:         &dest,
	}
	if err := opt.ProcessEnvVars("output-demo-"); err != nil {
		t.Fatalf("ProcessEnvVars error: %v", err)
	}
	if dest != "custom-host" {
		t.Errorf("dest = %q, want custom-host", dest)
	}
}

// TestProcessEnvVarsUnsetLeavesDefault verifies an unset env var leaves
// the destination untouched.
func TestProcessEnvVarsUnsetLeavesDefault(t *testing.T) {
	dest := "untouched"
	opt := PluginOption{
		Name: "host",
		Type: PluginOptionTypeString,
		Dest: &dest,
	}
	if err := opt.ProcessEnvVars("output-demo-"); err != nil {
		t.Fatalf("ProcessEnvVars error: %v", err)
	}
	if dest != "untouched" {
		t.Errorf("dest = %q, want untouched", dest)
	}
}

// TestProcessEnvVarsBadValues verifies parse errors for bad bool/int/uint
// env values.
func TestProcessEnvVarsBadValues(t *testing.T) {
	t.Run("bad-bool", func(t *testing.T) {
		var d bool
		t.Setenv("OUTPUT_DEMO_ENABLED", "notabool")
		opt := PluginOption{
			Name: "enabled",
			Type: PluginOptionTypeBool,
			Dest: &d,
		}
		if err := opt.ProcessEnvVars("output-demo-"); err == nil {
			t.Fatal("expected error for bad bool, got nil")
		}
	})
	t.Run("bad-int", func(t *testing.T) {
		var d int
		t.Setenv("OUTPUT_DEMO_COUNT", "notanint")
		opt := PluginOption{
			Name: "count",
			Type: PluginOptionTypeInt,
			Dest: &d,
		}
		if err := opt.ProcessEnvVars("output-demo-"); err == nil {
			t.Fatal("expected error for bad int, got nil")
		}
	})
	t.Run("bad-uint", func(t *testing.T) {
		var d uint
		t.Setenv("OUTPUT_DEMO_SIZE", "-1")
		opt := PluginOption{
			Name: "size",
			Type: PluginOptionTypeUint,
			Dest: &d,
		}
		if err := opt.ProcessEnvVars("output-demo-"); err == nil {
			t.Fatal("expected error for negative uint, got nil")
		}
	})
}

// TestProcessEnvVarsUnknownType verifies an unknown type errors when the
// env var is present.
func TestProcessEnvVarsUnknownType(t *testing.T) {
	t.Setenv("OUTPUT_DEMO_BAD", "x")
	opt := PluginOption{Name: "bad", Type: PluginOptionType(99)}
	if err := opt.ProcessEnvVars("output-demo-"); err == nil {
		t.Fatal("expected error for unknown type, got nil")
	}
}

// TestProcessConfig verifies type-correct values are applied for each
// option type from a plugin config map.
func TestProcessConfig(t *testing.T) {
	var (
		strDest  string
		boolDest bool
		intDest  int
		uintDest uint
	)
	data := map[any]any{
		"host":    "cfg-host",
		"enabled": true,
		"count":   11,
		"size":    9,
	}
	cases := []PluginOption{
		{Name: "host", Type: PluginOptionTypeString, Dest: &strDest},
		{Name: "enabled", Type: PluginOptionTypeBool, Dest: &boolDest},
		{Name: "count", Type: PluginOptionTypeInt, Dest: &intDest},
		{Name: "size", Type: PluginOptionTypeUint, Dest: &uintDest},
	}
	for i := range cases {
		if err := cases[i].ProcessConfig(data); err != nil {
			t.Fatalf("ProcessConfig error for %q: %v", cases[i].Name, err)
		}
	}
	if strDest != "cfg-host" {
		t.Errorf("strDest = %q, want cfg-host", strDest)
	}
	if !boolDest {
		t.Error("boolDest = false, want true")
	}
	if intDest != 11 {
		t.Errorf("intDest = %d, want 11", intDest)
	}
	if uintDest != 9 {
		t.Errorf("uintDest = %d, want 9", uintDest)
	}
}

// TestProcessConfigMissingKeyNoop verifies a missing key leaves the dest
// untouched and returns no error.
func TestProcessConfigMissingKeyNoop(t *testing.T) {
	dest := "untouched"
	opt := PluginOption{
		Name: "host",
		Type: PluginOptionTypeString,
		Dest: &dest,
	}
	if err := opt.ProcessConfig(map[any]any{"other": "x"}); err != nil {
		t.Fatalf("ProcessConfig error: %v", err)
	}
	if dest != "untouched" {
		t.Errorf("dest = %q, want untouched", dest)
	}
}

// TestProcessConfigTypeMismatch verifies a value of the wrong type errors
// for each option type.
func TestProcessConfigTypeMismatch(t *testing.T) {
	t.Run("string", func(t *testing.T) {
		var d string
		opt := PluginOption{
			Name: "host",
			Type: PluginOptionTypeString,
			Dest: &d,
		}
		if err := opt.ProcessConfig(map[any]any{"host": 123}); err == nil {
			t.Fatal("expected type error, got nil")
		}
	})
	t.Run("bool", func(t *testing.T) {
		var d bool
		opt := PluginOption{
			Name: "enabled",
			Type: PluginOptionTypeBool,
			Dest: &d,
		}
		if err := opt.ProcessConfig(map[any]any{"enabled": "yes"}); err == nil {
			t.Fatal("expected type error, got nil")
		}
	})
	t.Run("int", func(t *testing.T) {
		var d int
		opt := PluginOption{
			Name: "count",
			Type: PluginOptionTypeInt,
			Dest: &d,
		}
		if err := opt.ProcessConfig(map[any]any{"count": "x"}); err == nil {
			t.Fatal("expected type error, got nil")
		}
	})
	t.Run("uint-wrong-type", func(t *testing.T) {
		var d uint
		opt := PluginOption{
			Name: "size",
			Type: PluginOptionTypeUint,
			Dest: &d,
		}
		if err := opt.ProcessConfig(map[any]any{"size": "x"}); err == nil {
			t.Fatal("expected type error, got nil")
		}
	})
}

// TestProcessConfigNegativeUint verifies a negative int provided for a
// uint option is rejected.
func TestProcessConfigNegativeUint(t *testing.T) {
	var d uint
	opt := PluginOption{
		Name: "size",
		Type: PluginOptionTypeUint,
		Dest: &d,
	}
	if err := opt.ProcessConfig(map[any]any{"size": -1}); err == nil {
		t.Fatal("expected error for negative uint, got nil")
	}
}

// TestProcessConfigUnknownType verifies an unknown option type errors
// when the key is present.
func TestProcessConfigUnknownType(t *testing.T) {
	opt := PluginOption{Name: "bad", Type: PluginOptionType(99)}
	if err := opt.ProcessConfig(map[any]any{"bad": 1}); err == nil {
		t.Fatal("expected error for unknown type, got nil")
	}
}

// TestSplitAndTrim verifies comma-separated option values are split with
// surrounding whitespace removed and empty entries dropped, including the
// separator forms produced by YAML block scalars.
func TestSplitAndTrim(t *testing.T) {
	testCases := []struct {
		name     string
		input    string
		expected []string
	}{
		{
			name:     "empty string",
			input:    "",
			expected: nil,
		},
		{
			name:     "no separator",
			input:    "addr1aaa",
			expected: []string{"addr1aaa"},
		},
		{
			name:     "no whitespace",
			input:    "addr1aaa,addr1bbb",
			expected: []string{"addr1aaa", "addr1bbb"},
		},
		{
			name:  "YAML folded scalar (spaces after commas)",
			input: "addr1aaa, addr1bbb, addr1ccc",
			expected: []string{
				"addr1aaa",
				"addr1bbb",
				"addr1ccc",
			},
		},
		{
			name:     "YAML literal scalar (newlines and tabs)",
			input:    "addr1aaa,\n\taddr1bbb\n",
			expected: []string{"addr1aaa", "addr1bbb"},
		},
		{
			// A folded scalar only replaces newlines with spaces for equally
			// indented lines; a more-indented line keeps its newline and
			// leading indent
			name:  "YAML folded scalar (more-indented line)",
			input: "addr1aaa,\n  addr1bbb,\naddr1ccc",
			expected: []string{
				"addr1aaa",
				"addr1bbb",
				"addr1ccc",
			},
		},
		{
			// A blank line inside a folded scalar also yields a newline
			name:     "YAML folded scalar (blank line)",
			input:    "addr1aaa,\naddr1bbb",
			expected: []string{"addr1aaa", "addr1bbb"},
		},
		{
			name:     "leading and trailing whitespace",
			input:    "  addr1aaa  ",
			expected: []string{"addr1aaa"},
		},
		{
			name:     "empty entries dropped",
			input:    "addr1aaa,,  ,addr1bbb,",
			expected: []string{"addr1aaa", "addr1bbb"},
		},
		{
			name:     "whitespace only",
			input:    "  ,\n , ",
			expected: nil,
		},
	}
	for _, testCase := range testCases {
		t.Run(testCase.name, func(t *testing.T) {
			got := SplitAndTrim(testCase.input)
			if len(got) != len(testCase.expected) {
				t.Fatalf("got %q, want %q", got, testCase.expected)
			}
			for i := range got {
				if got[i] != testCase.expected[i] {
					t.Errorf("got %q, want %q", got, testCase.expected)
					break
				}
			}
		})
	}
}
