// Copyright 2026 Blink Labs Software
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package config

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"sync"
	"syscall"

	"gopkg.in/yaml.v3"
)

// saveLocks serializes concurrent SaveAtomic calls per destination
// path so the last-rename-wins lost-write hazard cannot bite callers
// that happen to save the same file from two goroutines. Keyed by
// filepath.Clean(path); not symlink-aware (two different paths to the
// same inode are not coalesced).
var saveLocks sync.Map

func saveLockFor(path string) *sync.Mutex {
	key := filepath.Clean(path)
	if m, ok := saveLocks.Load(key); ok {
		return m.(*sync.Mutex)
	}
	m, _ := saveLocks.LoadOrStore(key, &sync.Mutex{})
	return m.(*sync.Mutex)
}

// SaveAtomic encodes data as YAML and writes it durably to path via a
// unique temporary file + rename.
//
// Reliability guarantees:
//   - Encoder is explicitly Closed so all buffered bytes are flushed
//     before f.Close.
//   - syncFull (fsync on Linux/Windows, F_FULLFSYNC on macOS) runs
//     before f.Close so data blocks are durable on physical storage
//     prior to rename. Plain fsync on macOS does NOT provide this;
//     see fsync_darwin.go.
//   - The parent directory is fsynced after rename so the rename is
//     durable across a crash. Skipped on Windows where directory
//     fsync semantics differ; on filesystems that return ENOTSUP for
//     directory fsync (tmpfs, certain FUSE/SMB configurations) this
//     step is a no-op and the rename's durability is filesystem-
//     dependent.
//   - The temporary file name is generated by os.CreateTemp (O_EXCL +
//     random suffix), so concurrent callers cannot truncate each
//     other's in-flight tmp file.
//   - Calls to SaveAtomic with the same destination path are
//     serialized by a per-path sync.Mutex; concurrent calls do not
//     race the rename and no write is silently lost. (Different paths
//     do not contend; symlinks to the same inode are not coalesced.)
//
// SaveAtomic does not accept a context and will block for as long as
// the underlying syscalls take (potentially forever on a stalled
// disk). Callers that need cancellation responsiveness must wrap
// SaveAtomic externally; an in-package SaveAtomicCtx wrapper was
// considered and rejected because the leaked goroutine could
// out-of-order-clobber a subsequent successful save.
func SaveAtomic(path string, data any) error {
	mu := saveLockFor(path)
	mu.Lock()
	defer mu.Unlock()

	dir := filepath.Dir(path)
	if err := os.MkdirAll(dir, 0o700); err != nil {
		return fmt.Errorf("creating directory: %w", err)
	}

	// os.CreateTemp uses O_EXCL plus a random suffix where `*` sits
	// in the pattern, so the name is unique even if two callers hit
	// the same nanosecond.
	f, err := os.CreateTemp(dir, filepath.Base(path)+".tmp.*")
	if err != nil {
		return fmt.Errorf("creating temporary file: %w", err)
	}
	tmpFile := f.Name()
	// Single cleanup source: close the file if still open, and remove
	// the tmp file unless rename succeeded. Covers every error branch
	// (encode, flush, sync, close, rename) with one mechanism.
	// The os.Remove error is intentionally suppressed: best-effort
	// cleanup; nothing actionable to log because subsequent successful
	// saves use different unique tmp names — any leftover is debris,
	// not a correctness issue.
	renamed := false
	defer func() {
		if f != nil {
			_ = f.Close()
		}
		if !renamed {
			_ = os.Remove(tmpFile)
		}
	}()

	enc := yaml.NewEncoder(f)
	if err := enc.Encode(data); err != nil {
		return fmt.Errorf("encoding configuration: %w", err)
	}
	// Close flushes any buffered output and writes stream-terminating
	// events; without it, trailing bytes may stay in the encoder.
	if err := enc.Close(); err != nil {
		return fmt.Errorf("flushing encoder: %w", err)
	}

	if err := syncFull(f); err != nil {
		return fmt.Errorf("syncing temporary file: %w", err)
	}
	// The close-error branch below covers async write failures
	// (disk full, NFS commit, EIO). It is not exercised by unit
	// tests today — triggering it portably requires a filesystem
	// fault-injection layer that is out of scope for this package.
	err = f.Close()
	f = nil
	if err != nil {
		return fmt.Errorf("writing temporary file: %w", err)
	}

	if err := os.Rename(tmpFile, path); err != nil {
		return fmt.Errorf("renaming temporary file: %w", err)
	}
	renamed = true

	// Directory fsync so the rename itself is durable across a crash.
	// Skipped on Windows where directory fsync semantics differ. Real
	// I/O errors are propagated; filesystems that do not support
	// directory fsync (ENOTSUP / ENOSYS / EOPNOTSUPP — tmpfs and some
	// FUSE/SMB configurations) are treated as a no-op since failing
	// the save there would be incorrect.
	if runtime.GOOS != "windows" {
		d, derr := os.Open(dir)
		if derr != nil {
			return fmt.Errorf("opening parent directory: %w", derr)
		}
		defer d.Close()
		if err := d.Sync(); err != nil && !isUnsupportedFsync(err) {
			return fmt.Errorf("syncing parent directory: %w", err)
		}
	}
	return nil
}

// isUnsupportedFsync reports whether err is a filesystem-level "this
// operation is not supported here" rather than a real I/O failure.
// Used to keep SaveAtomic working on tmpfs / FUSE / SMB mounts where
// dir fsync is a documented no-op.
func isUnsupportedFsync(err error) bool {
	return errors.Is(err, syscall.ENOTSUP) ||
		errors.Is(err, syscall.ENOSYS) ||
		errors.Is(err, syscall.EOPNOTSUPP) ||
		errors.Is(err, syscall.EINVAL)
}
