// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Blink Labs",
            "url": "https://blinklabs.io",
            "email": "support@blinklabs.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/events": {
            "get": {
                "description": "Streams pipeline events using SSE, or WebSocket when an upgrade is requested and accepted. Rejected WebSocket handshakes do not fall back to SSE. Supports filtering on event types.",
                "produces": [
                    "text/event-stream",
                    "application/json"
                ],
                "summary": "Stream Blockchain Events",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Comma-separated list of event types to filter (e.g., input.block,input.transaction)",
                        "name": "types",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "default": true,
                        "description": "Whether to replay recent events from the ring buffer on connection",
                        "name": "replay",
                        "in": "query"
                    }
                ],
                "responses": {
                    "101": {
                        "description": "WebSocket protocol switch"
                    },
                    "200": {
                        "description": "Event Stream (SSE)",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Invalid WebSocket handshake",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "WebSocket origin rejected",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "405": {
                        "description": "Invalid WebSocket method",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Streaming or WebSocket upgrade unsupported",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/healthcheck": {
            "get": {
                "description": "Reports the health status of the running pipeline and registered checkers. Returns 503 if any registered checker is unhealthy.",
                "produces": [
                    "application/json"
                ],
                "summary": "Healthcheck Endpoint",
                "responses": {
                    "200": {
                        "description": "Healthy status response",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "503": {
                        "description": "Service Unavailable response",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/ping": {
            "get": {
                "description": "Returns a simple \"pong\" response to verify the API server is alive and reachable.",
                "produces": [
                    "text/plain"
                ],
                "summary": "Ping Endpoint",
                "responses": {
                    "200": {
                        "description": "pong",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v1/fcm": {
            "post": {
                "description": "Store a token in memory; configured persistence is best-effort. Available with the push output.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Store FCM Token",
                "parameters": [
                    {
                        "description": "FCM Token Request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/push.TokenRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created (empty body)"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/push.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/push.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/fcm/{token}": {
            "get": {
                "description": "Get an FCM token by its value. Available with the push output.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Get FCM Token",
                "parameters": [
                    {
                        "type": "string",
                        "description": "FCM Token",
                        "name": "token",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/push.TokenResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found (empty body)"
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/push.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete an FCM token by its value. Available with the push output.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Delete FCM Token",
                "parameters": [
                    {
                        "type": "string",
                        "description": "FCM Token",
                        "name": "token",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "404": {
                        "description": "Not Found (empty body)"
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/push.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/qrcode": {
            "get": {
                "description": "Returns an HTML page that loads QRious to encode an apiEndpoint JSON field containing the request host and FCM route. Available with the push output.",
                "produces": [
                    "text/html"
                ],
                "summary": "Generate QR Setup Page",
                "responses": {
                    "200": {
                        "description": "Interactive HTML Onboarding Page",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "push.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "push.TokenRequest": {
            "type": "object",
            "required": [
                "fcmToken"
            ],
            "properties": {
                "fcmToken": {
                    "type": "string"
                }
            }
        },
        "push.TokenResponse": {
            "type": "object",
            "properties": {
                "fcmToken": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "v1",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "Adder API",
	Description:      "Adder API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
